### ISSUE TITLE
about Prerequisite

### ISSUE THREAD

**Issue by ziziyaziziya** [FreeformRobotics/BORM#1]
I want to ask about yolov3/data analysis.py , where can I get this??

**Comment by hszhoushen** [comment]
Instead of using Yolov3 for object detection, we use the scene parsing model for semantic segmentation, where you can refer to the https://github.com/CSAILVision/sceneparsing for scene parsing model, we generate the path of images and corresponding object vectors based on the scene parsing results to the .json file.
